<table class="team_show-table">
	<tr style="text-align:center;">
		<td class="uppercase" colspan="2"><?php echo $this->data->title; ?></td>
		<td rowspan="7"><?php echo ($this->data->picture) ? $this->data->picture:'<img border="1" scr="" alt="team picture" />'; ?></td>
	</tr>
	<tr>
		<td><?php echo $this->translate('Discipline category'); ?></td>
		<td><?php echo $this->data->discipline_group; ?></td>
	</tr>
	<tr>
		<td><?php echo $this->translate('Discipline'); ?></td>
		<td><?php echo $this->data->discipline; ?></td>
	</tr>
	<tr>
		<td><?php echo $this->translate('Created at'); ?></td>
		<td><?php echo $this->data->created_at; ?></td>
	</tr>
	<tr>
		<td><?php echo $this->translate('Level'); ?></td>
		<td><?php echo $this->data->level; ?></td>
	</tr>
	<tr>
		<td><?php echo $this->translate('Preferred Gender'); ?></td>
		<td><?php echo $this->data->sex; ?></td>
	</tr>
	<tr>
		<td><?php echo $this->translate('Description'); ?></td>
		<td><?php echo $this->data->description; ?></td>
	</tr>
</table>

<?php 
	echo 'BACK';
	echo '<br />';
	echo 'NEXT';
	
?>