<?php
    $container = array(
        array(
            'label' => $this->translate('Edit'),
            'controller' => 'restriction',
            'action' => 'editgroup',
            'resource' => 'restriction.editgroup',
            'class' => 'link1',
        ),
        array(
            'label' => $this->translate('Link'),
            'controller' => 'restriction',
            'action' => 'linkresourcegroup',
            'resource' => 'restriction.linkresourcegroup',
            'class' => 'link1',
        ),
        array(
            'label' => $this->translate('Delete'),
            'controller' => 'restriction',
            'action' => 'deletegroup',
            'resource' => 'restriction.deletegroup',
            'class' => 'link1',
        ),
        array(
            'label' => $this->translate('Add new group'),
            'controller' => 'restriction',
            'action' => 'addgroup',
            'resource' => 'restriction.addgroup',
            'class' => 'link2',
        ),
    );
    $container = new Zend_Navigation($container);
    $this->container = $container; // WYSŁANIE BUTTONÓW DO TABLE GENERICA!!
    unset($container);
?>

<?php echo $this->render('/_common/table_generic.phtml'); ?>