<?php
    $container = array(
            array(
                'label' => $this->translate('Edit'),
                'controller' => 'restriction',
                'action' => 'editrole',
                'resource' => 'restriction.editrole',
                'class' => 'link1', // IMPORTANT!!
            ),
            array(
                'label' => $this->translate('Show'),
                'controller' => 'restriction',
                'action' => 'showrole',
                'resource' => 'restriction.showrole',
                'class' => 'link1', // IMPORTANT!!
            ),
            array(
                'label' => $this->translate('Delete'),
                'controller' => 'restriction',
                'action' => 'deleterole',
                'resource' => 'restriction.deleterole',
                'class' => 'link1', // IMPORTANT!!
            ),
            array(
                'label' => $this->translate('Add new role'),
                'controller' => 'restriction',
                'action' => 'addrole',
                'resource' => 'restriction.addrole',
                'class' => 'link2', // IMPORTANT!!
            ),
        );
    $container = new Zend_Navigation($container);
    $this->container = $container; // WYSŁANIE BUTTONÓW DO TABLE GENERICA!!
    unset($container);
?>

<?php echo $this->render('/_common/table_generic.phtml'); ?>